In [21]:
import pandas as pd

import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.utils import shuffle
df = pd.read_csv("Fake.csv")

tf = pd.read_csv("True.csv")

In [22]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

import nltk
from nltk.tokenize import sent_tokenize, word_tokenize
nltk.download('punkt')
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
stopwords = stopwords.words('english')

[nltk_data] Error loading stopwords: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1123)>
[nltk_data] Error loading punkt: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1123)>
[nltk_data] Error loading wordnet: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:1123)>

In [23]:
def frequency(value):
    result = {}
    for x in value.split():
        result[x] = result.get(x,0)+1
    return result
#dic_f = frequency(words_fake)
#dic_t = frequency(words_true)
for w in sorted(dic_t, key=dic_t.get, reverse=True):
    print(w, dic_t[w])

NameError: name 'dic_t' is not defined

In [24]:
df["type"] = 1
tf["type"] =0
kf = pd.concat([df,tf])
kf = shuffle(kf)

In [25]:
"""words_title = [x for x in "".join(kf.title).split() if len(x)>=4]
stopwords = stopwords.words('english')
title = {}
for x in words_title:
    if x not in stopwords:
        title[x] = title.get(x,0)+1
len(title)"""

'words_title = [x for x in "".join(kf.title).split() if len(x)>=4]\nstopwords = stopwords.words(\'english\')\ntitle = {}\nfor x in words_title:\n    if x not in stopwords:\n        title[x] = title.get(x,0)+1\nlen(title)'

In [26]:

def parse(sentence):
    return " ".join([lemmatizer.lemmatize(x.lower()) for x in word_tokenize(sentence) if x.lower() not in stopwords])

In [27]:
kf["n-text"] = kf.text.apply(parse)

In [28]:
kf["n-title"] = kf.title.apply(parse)

In [29]:
#all_text = " ".join(kf['n-title'] + kf["n-text"])

In [30]:
values = list(kf['n-title']) + list(kf["n-text"])
values[:10]

['muslim refugee dump garbage street protest insufficient wi-fi housing',
 'uk punter back early exit trump : bookmaker',
 'gold star parent confront black activist spike lee nfl flag kneeler [ video ]',
 'victory trump , judge toss suit foreign payment',
 'not-at-all-racist sheriff amazingly compare naacp kkk',
 'whoa ! flashback video andrew breitbart : “ ’ closet john podesta ? ”',
 'new poll show clinton opening 15 point lead trump dnc',
 "trump 's defense chief eye debut trip japan , south korea next week",
 'nafta negotiation round extended two day : mexico source',
 '# cnnblackmail trending network blackmail trump meme reddit user']

In [31]:
def frequency(values):
    result = {}
    
    for value in values:
        if not pd.isna(value):
            for x in word_tokenize(value):
                result[x] = result.get(x,0)+1
    return result
result = frequency(values)

In [32]:
key = pd.DataFrame({"words":result.keys()})

In [ ]:
key = key.reset_index().set_index('words')

In [36]:
#tokenize = lambda x: [key[key["words"]==y].index for y in word_tokenize(x)]
tokenize = lambda x: [key.loc[y] for y in word_tokenize(x)]

In [37]:
kf.loc[kf["n-text"].isnull(),["n-text"]] = ""

In [38]:

kf["nums-title"] = [tokenize(x) for x in kf["n-title"]]

In [23]:
kf.head()

,title,text,subject,date,n-title
9749,WATCH: GERALDO EMBARRASSES San Juan Mayor Who ...,Let s hope this angry leftist mayor doesn t pr...,politics,"Oct 4, 2017",watch : geraldo embarrasses san juan mayor sai...
460,Trump nominates Marvin Goodfriend for Fed gove...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"November 29, 2017",trump nominates marvin goodfriend fed governor...
4975,Tillerson used email alias at Exxon to talk cl...,NEW YORK (Reuters) - U.S. Secretary of State R...,politicsNews,"March 14, 2017",tillerson used email alias exxon talk climate ...
12286,U.S. military orders additional probe into Aug...,WASHINGTON (Reuters) - The head of U.S. forces...,worldnews,"December 14, 2017",u.s. military order additional probe august so...
1531,"As 2018 Obamacare deadline nears, U.S. states ...",NEW YORK (Reuters) - U.S. states have negotiat...,politicsNews,"September 27, 2017","2018 obamacare deadline nears , u.s. state bel..."

In [33]:
kf.to_csv("l.csv")

In [34]:
key.to_csv("key.csv")

In [39]:
kf

,title,text,subject,date,type,n-text,n-title,nums-title
21073,MUSLIM REFUGEES DUMP GARBAGE In Streets To Pro...,"Complaints over lack of wi-fi, no professional...",left-news,"Jan 24, 2016",1,"complaint lack wi-fi , professional cleaning s...",muslim refugee dump garbage street protest ins...,"[[0], [1], [2], [3], [4], [5], [6], [7], [8]]"
3757,UK punters back an early exit for Trump: bookm...,LONDON (Reuters) - British gamblers believe U....,politicsNews,"May 17, 2017",0,london ( reuters ) - british gambler believe u...,uk punter back early exit trump : bookmaker,"[[9], [10], [11], [12], [13], [14], [15], [16]]"
17894,GOLD STAR PARENTS Confront Black Activist Spik...,The backlash from angry fans has only gotten b...,left-news,"Sep 28, 2017",1,backlash angry fan gotten bigger refusal team ...,gold star parent confront black activist spike...,"[[17], [18], [19], [20], [21], [22], [23], [24..."
38,"In victory for Trump, judge tosses suit on for...",NEW YORK (Reuters) - A federal judge in New Yo...,politicsNews,"December 21, 2017",0,new york ( reuters ) - federal judge new york ...,"victory trump , judge toss suit foreign payment","[[31], [14], [32], [33], [34], [35], [36], [37]]"
6778,Not-At-All-Racist Sheriff Amazingly Compares ...,In a display of Olympic-level mental gymnastic...,News,"April 21, 2016",1,"display olympic-level mental gymnastics , sout...",not-at-all-racist sheriff amazingly compare na...,"[[38], [39], [40], [41], [42], [43]]"
...,...,...,...,...,...,...,...,...
5788,"Concerned about refugees, U.N. experts add to ...",(Reuters) - U.N. human rights experts warned t...,politicsNews,"February 1, 2017",0,( reuters ) - u.n. human right expert warned a...,"concerned refugee , u.n. expert add censure tr...","[[1485], [1], [32], [1282], [874], [6394], [13..."
9981,THE FUTURE BELONGS To AI And Whoever Masters I...,While all eyes are on North Korea and Melania ...,politics,"Sep 4, 2017",1,eye north korea melania stiletto rt competitio...,future belongs ai whoever master first rule world,"[[2216], [10641], [7460], [15816], [5945], [97..."
12099,"Mudslide in southern Chile kills five, at leas...",SANTIAGO (Reuters) - A mudslide on Saturday to...,worldnews,"December 16, 2017",0,santiago ( reuters ) - mudslide saturday tore ...,"mudslide southern chile kill five , least 15 m...","[[22219], [2437], [7111], [833], [1199], [32],..."
11123,California lethal injection plan spurs capital...,"SACRAMENTO, Calif. (Reuters) - Advocates and o...",politicsNews,"January 22, 2016",0,"sacramento , calif. ( reuters ) - advocate opp...",california lethal injection plan spur capital ...,"[[2836], [17642], [15972], [104], [7225], [101..."
2294,"Puerto Rico oversight board orders furloughs, ...",(Reuters) - Puerto Rico’s federally appointed ...,politicsNews,"August 4, 2017",0,( reuters ) - puerto rico ’ federally appointe...,"puerto rico oversight board order furlough , g...","[[887], [888], [5359], [4658], [382], [24217],..."

In [20]:
kf

,Unnamed: 0,title,text,subject,date,n-title,n-text
0,9749,WATCH: GERALDO EMBARRASSES San Juan Mayor Who ...,Let s hope this angry leftist mayor doesn t pr...,politics,"Oct 4, 2017",watch : geraldo embarrasses san juan mayor sai...,let hope angry leftist mayor prevent individua...
1,460,Trump nominates Marvin Goodfriend for Fed gove...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"November 29, 2017",trump nominates marvin goodfriend fed governor...,washington ( reuters ) - u.s. president donald...
2,4975,Tillerson used email alias at Exxon to talk cl...,NEW YORK (Reuters) - U.S. Secretary of State R...,politicsNews,"March 14, 2017",tillerson used email alias exxon talk climate ...,new york ( reuters ) - u.s. secretary state re...
3,12286,U.S. military orders additional probe into Aug...,WASHINGTON (Reuters) - The head of U.S. forces...,worldnews,"December 14, 2017",u.s. military order additional probe august so...,washington ( reuters ) - head u.s. force afric...
4,1531,"As 2018 Obamacare deadline nears, U.S. states ...",NEW YORK (Reuters) - U.S. states have negotiat...,politicsNews,"September 27, 2017","2018 obamacare deadline nears , u.s. state bel...",new york ( reuters ) - u.s. state negotiated b...
...,...,...,...,...,...,...,...
44893,17789,Trump to make working visit to UK in early 201...,LONDON (Reuters) - U.S. President Donald Trump...,worldnews,"October 11, 2017",trump make working visit uk early 2018 : report,london ( reuters ) - u.s. president donald tru...
44894,5583,America Shocked To Learn That Immigration Opp...,"Vox.com in conjunction with Morning Consult, a...",News,"July 6, 2016",america shocked learn immigration opponent act...,"vox.com conjunction morning consult , medium t..."
44895,12803,BREAKING: Wikileaks Email Release Exposes TWO-...,Huh? This could be one of the most damning ema...,politics,"Oct 7, 2016",breaking : wikileaks email release expose two-...,"huh ? could one damning email yet , reveals tr..."
44896,16038,"“HARRY, HARRY!” Crowd Yells Military Hero’s Na...",President Trump spoke at the first ever Celebr...,Government News,"Jul 2, 2017","“ harry , harry ! ” crowd yell military hero ’...",president trump spoke first ever celebrate fre...
44897,4887,Tillerson's use of email alias at Exxon 'entir...,(Reuters) - U.S. Secretary of State Rex Tiller...,politicsNews,"March 17, 2017",tillerson 's use email alias exxon 'entirely p...,( reuters ) - u.s. secretary state rex tillers...